[package]
name = "reduced-multiverse-debugging"
version = "0.1"
lean_version = "leanprover-community/lean:3.42.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "172f31797827df673ac8b8fb0d0129b45dc976aa"}
